#+STARTUP: showall indent hidestars

Чеклист для аудита смарт-контрактов.

* Проверка прав на доступ к функциям

Не должно быть функций, которыми по сценарию управляет Owner, доступных
для не-owner-а и наоборот.

* Неочевидный код

Как правило содержит ошибки если неясность видна с первого взгляда

* Ошибки с целочисленной арифметикой

- Деление тоже целочисленное (если не использзовать float)
- Деление на ноль

* Арифметическое переполнение

..и антипереполнение

* Неиспользование SafeMath при работе с числами

* Возможность транфера на произвольный адрес

Когда, например, происходит msg.sender.call. Может не быть ошибкой, если
функция с модификатором OnlyOwner.

* Отсутствие проверки параметров в функции доступной извне

Проверка на диапазон или хотя бы на не-ноль.

* Привязка времени к номеру блока

не особо адекватное решение

* Для каждой операции обычно должна быть обратная

Если есть депозит, должен быть вывод

* Проверять соответствие стандартам

Например Бинанс имеет свой стандарт ERC-20 который требует getOwner

* Other

Самое важное для проверки - это депозит и снятие

Manticore - изучить

[TODO:gmm] - Как искать флешлоаны? Смотреть, что msg.sender может быть
контрактом?

[TODO:gmm] - Просмотреть OpenZeppelin контракты
